version: 2.1

executors:
  python_docker:
    docker:
      - image: circleci/python:3.7-node-browsers-legacy

jobs:
  build:
    executor: python_docker
    steps:
      - checkout:
          - path: ~/project
      - run:
          command: |
            echo 'hello world'
            sudo chown -R circleci circleci .
            ./ci/setup.sh
            chmod -R +rwx ./ci


workflows:
  build_test_deploy:
    jobs:
      - build:
          name: build